# 浏览器自动化配置
# 基于Playwright的浏览器自动化参数设置

# 浏览器启动配置
BROWSER_LAUNCH:
  # 浏览器类型选择
  browser_type: "chromium"  # chromium, firefox, webkit
  
  # 启动参数
  launch_options:
    headless: false  # 调试时设为false，生产环境可设为true
    slow_mo: 100  # 操作间延迟(毫秒)，便于观察
    devtools: false  # 是否打开开发者工具
    
  # 浏览器参数
  args:
    - "--no-sandbox"
    - "--disable-setuid-sandbox"
    - "--disable-dev-shm-usage"
    - "--disable-accelerated-2d-canvas"
    - "--no-first-run"
    - "--no-zygote"
    - "--disable-gpu"
    - "--window-size=1920,1080"
    
  # 环境变量
  env:
    DISPLAY: ":99"  # 用于无头环境

# 页面配置
PAGE_CONFIG:
  # 视口设置
  viewport:
    width: 1920
    height: 1080
    device_scale_factor: 1
    
  # 用户代理
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 LowCodeBot/1.0"
  
  # 页面超时设置
  timeouts:
    default_timeout: 30000  # 默认超时30秒
    navigation_timeout: 60000  # 页面导航超时60秒
    
  # 等待策略
  wait_strategies:
    default_wait_until: "networkidle"  # load, domcontentloaded, networkidle
    custom_wait_conditions:
      - "load"
      - "domcontentloaded"
      - "networkidle"

# 元素定位配置
ELEMENT_LOCATION:
  # 等待策略
  wait_for_selector:
    timeout: 30000
    state: "visible"  # attached, detached, visible, hidden
    
  # 重试机制
  retry_config:
    max_attempts: 3
    retry_delay: 1000  # 毫秒
    exponential_backoff: true
    
  # 智能定位策略
  locator_strategies:
    priority_order:
      - "data-testid"
      - "id"
      - "name"
      - "class"
      - "xpath"
      - "css"
    
    fallback_enabled: true
    use_ai_enhanced_location: true

# 操作配置
OPERATION_CONFIG:
  # 点击操作
  click:
    force: false
    timeout: 30000
    trial: false
    delay: 100  # 点击后延迟
    
  # 输入操作
  fill:
    force: false
    timeout: 30000
    clear_before_fill: true
    
  # 选择操作
  select:
    force: false
    timeout: 30000
    
  # 键盘操作
  keyboard:
    delay: 50  # 按键间延迟
    
  # 鼠标操作
  mouse:
    delay: 100  # 鼠标操作延迟

# 截图配置
SCREENSHOT_CONFIG:
  # 基本设置
  enabled: true
  format: "png"  # png, jpeg
  quality: 90  # JPEG质量(1-100)
  
  # 截图时机
  capture_timing:
    before_operation: true
    after_operation: true
    on_error: true
    on_validation: true
    
  # 截图类型
  screenshot_types:
    full_page: true
    viewport_only: false
    element_only: false
    
  # 存储配置
  storage:
    base_path: "screenshots"
    organize_by_date: true
    max_files_per_session: 100
    auto_cleanup_old_files: true
    retention_days: 7

# 错误处理配置
ERROR_HANDLING:
  # 重试策略
  retry_strategy:
    max_retries: 3
    base_delay: 1000  # 毫秒
    max_delay: 10000  # 毫秒
    exponential_base: 2
    
  # 错误类型处理
  error_types:
    timeout_error:
      action: "retry"
      max_retries: 2
      
    element_not_found:
      action: "retry_with_fallback"
      fallback_strategies:
        - "wait_longer"
        - "try_alternative_selector"
        - "refresh_page"
        
    network_error:
      action: "retry"
      max_retries: 3
      delay: 2000
      
    javascript_error:
      action: "log_and_continue"
      
  # 恢复策略
  recovery_strategies:
    page_crash:
      action: "restart_browser"
      
    session_expired:
      action: "re_authenticate"
      
    memory_leak:
      action: "restart_session"

# 性能优化配置
PERFORMANCE_OPTIMIZATION:
  # 资源加载
  resource_loading:
    block_images: false
    block_stylesheets: false
    block_fonts: false
    block_media: false
    
  # 缓存设置
  cache:
    enabled: true
    clear_on_start: false
    
  # 并发控制
  concurrency:
    max_concurrent_pages: 3
    max_concurrent_operations: 5
    
  # 内存管理
  memory_management:
    auto_close_unused_pages: true
    page_idle_timeout: 300000  # 5分钟
    max_pages_per_context: 10

# 调试配置
DEBUG_CONFIG:
  # 调试模式
  debug_mode: true
  
  # 日志记录
  logging:
    console_api: true
    page_errors: true
    request_response: true
    
  # 调试工具
  debug_tools:
    enable_devtools: false
    pause_on_error: false
    step_by_step_mode: false
    
  # 录制功能
  recording:
    enabled: false
    video_path: "recordings"
    video_size: "1920x1080"

# 环境适配配置
ENVIRONMENT_ADAPTATION:
  # 不同环境配置
  development:
    headless: false
    slow_mo: 200
    devtools: true
    
  testing:
    headless: true
    slow_mo: 50
    devtools: false
    
  production:
    headless: true
    slow_mo: 0
    devtools: false
    
  # 操作系统适配
  os_specific:
    windows:
      executable_path: null
      
    linux:
      executable_path: null
      display: ":99"
      
    macos:
      executable_path: null
